### ISSUE TITLE
ERROR when Uglify

### ISSUE THREAD

**Issue by eric7578** [draft-js-plugins/find-with-regex#3]
I am using the drafjs-mention-plugin, but when I try to build in the production, I got this error.
The version of the mention-plugin is `2.1.0`

`ERROR in vendor.c0939953.js from UglifyJs`

I digging into the `node_modules/find-with-regex/build/index.js`
I found that maybe it's the **first line** of the following code that causing this error

```
import 'draft-js';

var findWithRegex = function findWithRegex(regex, contentBlock, callback) {
  // Get the text from the contentBlock
  var text = contentBlock.getText();
  var matchArr = void 0;
  var start = void 0; // eslint-disable-line
  // Go through all matches in the text and return the indizes to the callback
  while ((matchArr = regex.exec(text)) !== null) {
    // eslint-disable-line
    if (matchArr.index === regex.lastIndex) {
      regex.lastIndex++;
    }
    start = matchArr.index;
    callback(start, start + matchArr[0].length);
  }
};

```

**Comment by mbutsykin** [comment]
+1, build version of find-with-regex@1.1.0 (`build/index.js`) contains not built source

**Comment by eric7578** [comment]
@mbutsykin I found that the npm version matters, in my case if the npm version is v3.x.x it brokes. However I tried to switch to v6.0.0 it works fine. Is it the same in your case?

**Comment by andreieftimie** [comment]
We reverted to `1.0.2` to overcome this issue.

**Comment by juliankrispel** [comment]
fixed in latest version!

**Comment by juliankrispel** [comment]
thanks for the report folks!
