### ISSUE TITLE
Forget to bump version to 1.1.3?

### ISSUE THREAD

**Issue by hongbo-miao** [draft-js-plugins/find-with-regex#5]
This PR https://github.com/draft-js-plugins/draft-js-plugins/commit/d55e2b2ce140e7cc1f4762d267a882817d59e0d5
made plugins rely on ^1.1.3

Forget to bump version to 1.1.3?

**Comment by modao** [comment]
Seems so...

**Comment by juliankrispel** [comment]
nope - as you can see it's live - https://www.npmjs.com/package/find-with-regex - it might not have been pushed to this master branch but it's on npm ...
