### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by wxxian001** [draft-js-plugins/find-with-regex#7]
SyntaxError: Unexpected token: keyword (default) [./~/_find-with-regex@1.1.2@find-with-regex/build/index.js:17,0]

**Comment by kurenov** [comment]
@wxxian001 I think this issue was resolved in version 1.1.**3**. But there is still similar issue, but related to `import` now

**Comment by juliankrispel** [comment]
@kurenov what issue?

**Comment by juliankrispel** [comment]
@wxxian001 try 1.1.3 :+1:

**Comment by wxxian001** [comment]
@juliankrispel thx
